# fly.toml file generated for protohackers-echo on 2023-02-05T14:09:18-05:00

app = "protohackers-echo"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
PORT = "8888"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 8888
protocol = "tcp"

[[services.ports]]
port = "8888"
